apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnopresources.nop.example.org
spec:
  compositeTypeRef:
    apiVersion: nop.example.org/v1alpha1
    kind: XNopResource
  resources:
  - name: nop-resource-1
    base:
      apiVersion: nop.crossplane.io/v1alpha1
      kind: NopResource
      spec:
        forProvider:
          fields:
            masterAuthorizedNetworksConfig:
            - cidrBlocks:
              - cidrBlock: 10.2.16.0/28
                displayName: bastion
          conditionAfter:
          - conditionType: Ready
            conditionStatus: "False"
            time: 0s
          - conditionType: Ready
            conditionStatus: "True"
            time: 10s
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.coolField
      toFieldPath: metadata.annotations[cool-field]
      transforms:
      - type: string
        string:
         type: Convert
         convert: ToUpper
    - type: FromCompositeFieldPath
      fromFieldPath: spec.authorizedNetworks
      toFieldPath: spec.forProvider.fields.masterAuthorizedNetworksConfig[0].cidrBlocks
      policy:
        mergeOptions:
            appendSlice: true
