apiVersion: nop.example.org/v1alpha1
kind: NopResource
metadata:
  namespace: default
  name: apiextensions-composition-pandt
spec:
  coolField: "foo"
  compositionRevisionSelector:
    matchLabels:
      semverFull: "v1.22.6"